export default {
  "recharge_amount": "Top up amount",
  "nickname": "Nickname",
  "confirm_recharge": "Confirm top up",
  "confirm": "Confirm",
  "account_recharge": "Top up",
  "choose_recharge_method": "Select a top-up method",
  "choose_recharge_amount": "Select a top-up amount",
  "confirm_payment": "Confirm payment",
  "text1": "Payment Result",
  "text2": "Details",
  "text3": "An exception occurred in the service, please try again",
  "text4": "Payment Status Confirmation",
  "text5": "Have you completed the payment?",
  "text6": "Yes",
  "text7": "Payment Processing",
  "text8": "Payment Success",
  "text9": "Details",
  "text10": "Payment Time",
  "text11": "Payment Channel",
  "text12": "Order Number",
  "text13": "No",
  "text14": "Diamonds",
  "text15": "Reseller",
  "text16": "Diamonds Top Up",
  "text17": "Reseller Top Up"
}