export default {
    "text1": "notice",
    "text2": "Are you sure you want to modify the withdrawal account information?",
    "text3": "Cancel",
    "text4": "Confirm",
    "text5": "Min $1 each time",
    "text6": "Insufficient withdrawal amount",
    "text7": "Payoneer account format error",
    "text8": "Details",
    "text9": "Withdrawal Records",
    "text10": "Input the withdrawal amount",
    "text11": " Min $1 each time",
    "text12": "Min $1 each time",
    "text13": "Insufficient withdrawal amount",
    "text14": "Withdrawal fee ",
    "text15": "The actual amount received is",
    "text16": "Choose the withdrawal method",
    "text17": "To Agency Owner Account",
    "text18": "Complete withdrawal information",
    "text19": "Account",
    "text20": "Click to input Payoneer account，the format is email",
    "text21": "Please make sure that the information you input is correct, otherwise the withdrawal won't be successful",
    "text22": "Please note that after choosing this method to withdraw, the balance will immediately enter the account of the agency owner, and the agency owner needs to withdraw to his/her own bank card or digital wallet again. The actual arrival time and amount are subject to the final withdrawal of the agency owner.",
    "text23": "After withdrawing to the agency owner's account, it cannot be returned. Please confirm it before proceeding. Due to the channel rate of the digital wallet and bank card, this withdrawal is expected to pay a handling fee of %5.",
    "text24": "Register with Payoneer",
    "text25": "Use it the first time, you need to go to the Payoneer official website to register",
    "text26": "Go",
    "text27": "Confirm withdrawal information",
    "text28": "Withdrawal method:",
    "text29": "Account",
    "text30": "Withdrawal Amount",
    "text31": "Handling Fee",
    "text32": "Actual Amount",
    "text33": "Are you sure to withdraw to the agency owner's account?",
    "text34": "Estimated Handling Fee",
    "text35": "Estimated Actual Amount",
    "text36": "Submit Application",
    "text37": "Processing",
    "text38": "Withdrawal Success",
    "text39": "Withdrawal Failed",
    "text40": "Successful application",
    "text41": "Actual Amount",
    "text42": "Account",
    "text43": "Withdrawal date",
    "text44": "The withdrawal application will be reviewed and completed in 5 working days, and the actual arrival time is subject to the processing by the bank or digital wallet;",
    "text45": "You can go to【Wallet-Withdrawal-",
    "text46": "] to query the progress;",
    "text47": "Withdrawal Application",
    "text48": "Withdrawal",
    "text49": "successful transfer"
}