export default {
  "recharge_amount": "Yükle miktar",
  "nickname": "Takma adı",
  "confirm_recharge": "Yükle",
  "confirm": "Onayla",
  "account_recharge": "Yükle",
  "choose_recharge_method": "Yükle yolu seç",
  "choose_recharge_amount": "Yükle miktar seç",
  "confirm_payment": "Öde",
  "text1": "Ödeme Sonucu",
  "text2": "Detaylar",
  "text3": "Hizmette bir istisna oluştu, lütfen tekrar deneyin",
  "text4": "Ödeme Durumu Onayı",
  "text5": "Ödemeyi tamamladınız mı?",
  "text6": "Evet",
  "text7": "Odeme yapiliyor",
  "text8": "Başarılı ödeme!",
  "text9": "Detaylar",
  "text10": "Ödeme Süresi",
  "text11": "Ödeme Kanalı",
  "text12": "Sipariş numarası",
  "text13": "Numara",
  "text14": "elmaslar",
  "text15": "bayi",
  "text16": "elmas şarjı",
  "text17": "Bayi Doldurma"
}