export default {
    "text1": "hatırlatmak",
    "text2": "Para çekme hesabı bilgilerini değiştirmek istediğinizden emin misiniz?",
    "text3": "İptal et",
    "text4": "onaylamak",
    "text5": "Her seferinde en az $1",
    "text6": "Yetersiz para çekme miktarı",
    "text7": "Payoneer hesap formatı hatası",
    "text8": "Detaylar",
    "text9": "Para Çekme Kayıtları",
    "text10": "Para çekme miktarını girin",
    "text11": " Her seferinde en az $1",
    "text12": "Her seferinde en az $1",
    "text13": "Yetersiz para çekme miktarı",
    "text14": "Para çekme ücreti",
    "text15": "Gerçek Tutar",
    "text16": "Para çekme yöntemini seçin",
    "text17": "Ajans Sahibi Hesabına",
    "text18": "Tam para çekme bilgileri",
    "text19": "Hesap",
    "text20": "Payoneer hesabını girmek için tıklayın，Biçim e-postadır",
    "text21": "Lütfen girdiğiniz bilgilerin doğru olduğundan emin olun, aksi takdirde para çekme işlemi başarılı olmayacaktır.",
    "text22": "Lütfen bu yöntemi seçtikten sonra bakiyenin hemen acente sahibinin hesabına gireceğini ve acente sahibinin tekrar kendi banka kartına veya dijital cüzdanına çekmesi gerektiğini unutmayın. Gerçek varış zamanı ve miktarı, acente sahibinin nihai olarak geri çekilmesine tabidir.",
    "text23": "Acente sahibinin hesabına çekildikten sonra iade edilemez. Lütfen devam etmeden önce onaylayın. Dijital cüzdan ve banka kartının kanal oranı nedeniyle, bu para çekme işleminin %5 işlem ücreti ödemesi bekleniyor.",
    "text24": "Payoneer'a kaydolun",
    "text25": "İlk kez kullanın, kayıt olmak için Payoneer resmi web sitesine gitmeniz gerekir.",
    "text26": "Gitmek",
    "text27": "Para çekme bilgilerini onaylayın",
    "text28": "Para çekme yöntemi",
    "text29": "Hesap",
    "text30": "Para Çekme Tutarı",
    "text31": "Elleçleme Ücreti",
    "text32": "Gerçek Tutar",
    "text33": "Ajans sahibinin hesabına çekeceğinizden emin misiniz?",
    "text34": "Tahmini Taşıma Ücreti",
    "text35": "Tahmini Gerçek Tutar",
    "text36": "Başvuruyu Gönder",
    "text37": "İşleme",
    "text38": "Para Çekme Başarısı",
    "text39": "Para Çekme Başarısız",
    "text40": "Başarılı uygulama",
    "text41": "Gerçek Tutar",
    "text42": "Hesap",
    "text43": "Çekilme tarihi",
    "text44": "Para çekme başvurusu 5 iş günü içinde incelenip tamamlanacak ve gerçek varış zamanı banka veya dijital cüzdan tarafından işleme tabi tutulacaktır;",
    "text45": "yapabilirsiniz【cüzdan-Çekil-",
    "text46": "】sorgu ilerlemesi;",
    "text47": "Başvuruyu Gönder",
    "text48": "Çekil",
    "text49": "başarılı transfer"
}