// 商品定价
export const products = {
    'ali': [
        { name: 'ali.1', value: '0.75元', display: '10' },
        { name: 'ali.6', value: '4.5元', display: '60' },
        { name: 'ali.10', value: '7.5元', display: '100' },
        { name: 'ali.30', value: '22.5元', display: '300' },
        { name: 'ali.50', value: '37.5元', display: '500' },
        { name: 'ali.100', value: '75元', display: '1000' },
        { name: 'ali.200', value: '150元', display: '2000' },
        { name: 'ali.500', value: '375元', display: '5000' },
        { name: 'ali.1000', value: '750元', display: '10000' },
    ],
    'p99': [
        { name: 'p99.11', value: '50點', display: '110', vat: '5' },
        { name: 'p99.22', value: '100點', display: '220', vat: '5' },
        { name: 'p99.34', value: '150點', display: '340', vat: '5' },
        { name: 'p99.68', value: '300點', display: '680', vat: '5' },
        { name: 'p99.102', value: '450點', display: '1020', vat: '5' },
        { name: 'p99.114', value: '500點', display: '1140', vat: '5' },
        { name: 'p99.228', value: '1000點', display: '2280', vat: '5' },
        { name: 'p99.273', value: '1200點', display: '2730', vat: '5' },
        { name: 'p99.456', value: '2000點', display: '4560', vat: '5' },
        { name: 'p99.684', value: '3000點', display: '6840', vat: '5' },
        { name: 'p99.1140', value: '5000點', display: '11400', vat: '5' },
        { name: 'p99.2281', value: '10000點', display: '22810', vat: '5' },
        { name: 'p99.4562', value: '20000點', display: '45620', vat: '5' },
        { name: 'p99.11406', value: '50000點', display: '114060', vat: '5' },
    ],
    //p99 的電信付費
    'p99.tel': [
        { name: 'p99.tel.10', value: '41TWD', display: '100', vat: '5' },
        { name: 'p99.tel.30', value: '122TWD', display: '300', vat: '5' },
        { name: 'p99.tel.50', value: '204TWD', display: '500', vat: '5' },
        // { name: 'p99.tel.100', value: '407TWD', display: '1000', vat: '5' },
        // { name: 'p99.tel.360', value: '1464TWD', display: '3600', vat: '5' },
    ],
    //p99 的金融支付
    'p99.card': [
        //{name : 'p99.card.11', value : '50TWD', display: '110', vat : '5' },
        { name: 'p99.card.15', value: '57TWD', display: '150', vat: '5' },
        { name: 'p99.card.30', value: '113TWD', display: '300', vat: '5' },
        { name: 'p99.card.50', value: '188TWD', display: '500', vat: '5' },
        { name: 'p99.card.100', value: '375TWD', display: '1000', vat: '5' },
        { name: 'p99.card.500', value: '1872TWD', display: '5000', vat: '5' },
        { name: 'p99.card.1000', value: '3744TWD', display: '10000', vat: '5' },
        { name: 'p99.card.2000', value: '7488TWD', display: '20000', vat: '5' },
    ],
    'fomo.wechat': [
        { name: 'fomo.9', value: '1USD', display: '90' },
        { name: 'fomo.19', value: '2USD', display: '190' },
        { name: 'fomo.58', value: '6USD', display: '580' },
        { name: 'fomo.176', value: '18USD', display: '1760' },
        { name: 'fomo.352', value: '36USD', display: '3520' },
        { name: 'fomo.705', value: '72USD', display: '7050' },
        { name: 'fomo.1058', value: '108USD', display: '10580' },
        { name: 'fomo.1960', value: '200USD', display: '19600' },
        { name: 'fomo.4900', value: '500USD', display: '49000' },
        { name: 'fomo.9800', value: '1000USD', display: '98000' },
    ],
    'fomo.ali': [
        { name: 'fomo.ali.28', value: '3USD', display: '280' },
        { name: 'fomo.ali.48', value: '5USD', display: '480' },
        { name: 'fomo.ali.96', value: '10USD', display: '960' },
        { name: 'fomo.ali.193', value: '20USD', display: '1930' },
        { name: 'fomo.ali.482', value: '50USD', display: '4820' },
        { name: 'fomo.ali.965', value: '100USD', display: '9650' },
        { name: 'fomo.ali.1930', value: '200USD', display: '19300' },
        // { name: 'fomo.ali.4825', value: '500USD', display: '48250' },
        // { name: 'fomo.ali.9650', value: '1000USD', display: '96500' },
    ],
    'fomo.alisgp': [
        { name: 'fomo.ali.8', value: '1USD', display: '80', vat: '7' },
        { name: 'fomo.ali.17', value: '2USD', display: '170', vat: '7' },
        { name: 'fomo.ali.44', value: '5USD', display: '440', vat: '7' },
        { name: 'fomo.ali.89', value: '10USD', display: '890', vat: '7' },
        { name: 'fomo.ali.179', value: '20USD', display: '1790', vat: '7' },
        { name: 'fomo.ali.447', value: '50USD', display: '4470', vat: '7' },
        { name: 'fomo.ali.895', value: '100USD', display: '8950', vat: '7' },
        { name: 'fomo.ali.1790', value: '200USD', display: '17900', vat: '7' },
        // { name: 'fomo.ali.4475', value: '500USD', display: '44750', vat: '7' },
        // { name: 'fomo.ali.8950', value: '1000USD', display: '89500', vat: '7' },
    ],
    'fomo.card': [
        { name: 'fomo.card.72', value: '8USD', display: '720' },
        { name: 'fomo.card.147', value: '16USD', display: '1470' },
        { name: 'fomo.card.270', value: '29USD', display: '2700' },
        { name: 'fomo.card.458', value: '49USD', display: '4580' },
        { name: 'fomo.card.740', value: '79USD', display: '7400' },
        { name: 'fomo.card.928', value: '99USD', display: '9280' },
        { name: 'fomo.card.1492', value: '159USD', display: '14920' },
        { name: 'fomo.card.1774', value: '189USD', display: '17740' },
        { name: 'fomo.card.2432', value: '259USD', display: '24320' },
    ],
    'paypal': [
        //{name : 'paypal.6', value : '1USD', display: '60'},
        { name: 'paypal.25', value: '3USD', display: '250' },
        { name: 'paypal.54', value: '6USD', display: '540' },
        { name: 'paypal.111', value: '12USD', display: '1110' },
        { name: 'paypal.225', value: '24USD', display: '2250' },
        { name: 'paypal.475', value: '50USD', display: '4750' }
    ],
    'coda': [],
    'coda.sgp_starhub': [
        { name: "coda.sgp_starhub.13", value: "3SGD", display: "130", vat: '7' },
        { name: "coda.sgp_starhub.22", value: "5SGD", display: "220", vat: '7' },
        { name: "coda.sgp_starhub.44", value: "10SGD", display: "440", vat: '7' },
        { name: "coda.sgp_starhub.89", value: "20SGD", display: "890", vat: '7' },
        { name: "coda.sgp_starhub.224", value: "50SGD", display: "2240", vat: '7' },
        { name: "coda.sgp_starhub.269", value: "60SGD", display: "2690", vat: '7' },
    ],
    'coda.sgp_m1': [
        { name: "coda.sgp_m1.13", value: "3SGD", display: "130", vat: '7' },
        { name: "coda.sgp_m1.22", value: "5SGD", display: "220", vat: '7' },
        { name: "coda.sgp_m1.44", value: "10SGD", display: "440", vat: '7' },
        { name: "coda.sgp_m1.89", value: "20SGD", display: "890", vat: '7' },
        { name: "coda.sgp_m1.224", value: "50SGD", display: "2240", vat: '7' },
        { name: "coda.sgp_m1.269", value: "60SGD", display: "2690", vat: '7' },
    ],
    'coda.sgp_grabpay': [
        { name: "coda.sgp_grabpay.6", value: "1SGD", display: "60", vat: '7' },
        { name: "coda.sgp_grabpay.18", value: "3SGD", display: "180", vat: '7' },
        { name: "coda.sgp_grabpay.30", value: "5SGD", display: "300", vat: '7' },
        { name: "coda.sgp_grabpay.61", value: "10SGD", display: "610", vat: '7' },
        { name: "coda.sgp_grabpay.122", value: "20SGD", display: "1220", vat: '7' },
        { name: "coda.sgp_grabpay.306", value: "50SGD", display: "3060", vat: '7' },
        { name: "coda.sgp_grabpay.613", value: "100SGD", display: "6130", vat: '7' },
        { name: "coda.sgp_grabpay.1227", value: "200SGD", display: "12270", vat: '7' },
        { name: "coda.sgp_grabpay.1841", value: "300SGD", display: "18410", vat: '7' },
    ],
    'coda.mys_grabpay': [
        { name: "coda.mys_grabpay.2", value: "1MYR", display: "20", vat: '6' },
        { name: "coda.mys_grabpay.6", value: "3MYR", display: "60", vat: '6' },
        { name: "coda.mys_grabpay.10", value: "5MYR", display: "100", vat: '6' },
        { name: "coda.mys_grabpay.20", value: "10MYR", display: "200", vat: '6' },
        { name: "coda.mys_grabpay.40", value: "20MYR", display: "400", vat: '6' },
        { name: "coda.mys_grabpay.101", value: "50MYR", display: "1010", vat: '6' },
        { name: "coda.mys_grabpay.203", value: "100MYR", display: "2030", vat: '6' },
        { name: "coda.mys_grabpay.406", value: "200MYR", display: "4060", vat: '6' },
        { name: "coda.mys_grabpay.1017", value: "500MYR", display: "10170", vat: '6' },
    ],
    'coda.mys_touchgo': [
        { name: "coda.mys_touchgo.2", value: "1MYR", display: "20", vat: '6' },
        { name: "coda.mys_touchgo.6", value: "3MYR", display: "60", vat: '6' },
        { name: "coda.mys_touchgo.10", value: "5MYR", display: "100", vat: '6' },
        { name: "coda.mys_touchgo.20", value: "10MYR", display: "200", vat: '6' },
        { name: "coda.mys_touchgo.40", value: "20MYR", display: "400", vat: '6' },
        { name: "coda.mys_touchgo.101", value: "50MYR", display: "1010", vat: '6' },
        { name: "coda.mys_touchgo.203", value: "100MYR", display: "2030", vat: '6' },
        { name: "coda.mys_touchgo.406", value: "200MYR", display: "4060", vat: '6' },
        { name: "coda.mys_touchgo.1017", value: "500MYR", display: "10170", vat: '6' },
        { name: "coda.mys_touchgo.2034", value: "1000MYR", display: "20340", vat: '6' },
        { name: "coda.mys_touchgo.6104", value: "3000MYR", display: "61040", vat: '6' },
        { name: "coda.mys_touchgo.10174", value: "5000MYR", display: "101740", vat: '6' },
    ],
    'coda.mys_boostewallet': [
        { name: "coda.mys_boostewallet.2", value: "1MYR", display: "20", vat: '6' },
        { name: "coda.mys_boostewallet.6", value: "3MYR", display: "60", vat: '6' },
        { name: "coda.mys_boostewallet.10", value: "5MYR", display: "100", vat: '6' },
        { name: "coda.mys_boostewallet.20", value: "10MYR", display: "200", vat: '6' },
        { name: "coda.mys_boostewallet.40", value: "20MYR", display: "400", vat: '6' },
        { name: "coda.mys_boostewallet.101", value: "50MYR", display: "1010", vat: '6' },
        { name: "coda.mys_boostewallet.203", value: "100MYR", display: "2030", vat: '6' },
        { name: "coda.mys_boostewallet.406", value: "200MYR", display: "4060", vat: '6' },
        { name: "coda.mys_boostewallet.1017", value: "500MYR", display: "10170", vat: '6' },
        { name: "coda.mys_boostewallet.2034", value: "1000MYR", display: "20340", vat: '6' },
        { name: "coda.mys_boostewallet.6104", value: "3000MYR", display: "61040", vat: '6' },
        { name: "coda.mys_boostewallet.10174", value: "5000MYR", display: "101740", vat: '6' },
    ],
    'coda.mys_celcom': [
        { name: "coda.mys_celcom.2", value: "2MYR", display: "20", vat: '6' },
        { name: "coda.mys_celcom.7", value: "5MYR", display: "70", vat: '6' },
        { name: "coda.mys_celcom.14", value: "10MYR", display: "140", vat: '6' },
        { name: "coda.mys_celcom.29", value: "20MYR", display: "290", vat: '6' },
        { name: "coda.mys_celcom.74", value: "50MYR", display: "740", vat: '6' },
        { name: "coda.mys_celcom.149", value: "100MYR", display: "1490", vat: '6' },
        { name: "coda.mys_celcom.179", value: "120MYR", display: "1790", vat: '6' },
    ],
    'coda.mys_umobile': [
        { name: "coda.mys_umobile.2", value: "2MYR", display: "20", vat: '6' },
        { name: "coda.mys_umobile.7", value: "5MYR", display: "70", vat: '6' },
        { name: "coda.mys_umobile.14", value: "10MYR", display: "140", vat: '6' },
        { name: "coda.mys_umobile.29", value: "20MYR", display: "290", vat: '6' },
        { name: "coda.mys_umobile.44", value: "30MYR", display: "440", vat: '6' },
    ],
    'coda.mys_maxis': [
        { name: "coda.mys_maxis.2", value: "2MYR", display: "20", vat: '6' },
        { name: "coda.mys_maxis.7", value: "5MYR", display: "70", vat: '6' },
        { name: "coda.mys_maxis.14", value: "10MYR", display: "140", vat: '6' },
        { name: "coda.mys_maxis.29", value: "20MYR", display: "290", vat: '6' },
        { name: "coda.mys_maxis.74", value: "50MYR", display: "740", vat: '6' },
        { name: "coda.mys_maxis.149", value: "100MYR", display: "1490", vat: '6' },
    ],
    'coda.mys_digi': [
        { name: "coda.mys_digi.2", value: "2MYR", display: "20", vat: '6' },
        { name: "coda.mys_digi.7", value: "5MYR", display: "70", vat: '6' },
        { name: "coda.mys_digi.14", value: "10MYR", display: "140", vat: '6' },
        { name: "coda.mys_digi.29", value: "20MYR", display: "290", vat: '6' },
        { name: "coda.mys_digi.74", value: "50MYR", display: "740", vat: '6' },
        { name: "coda.mys_digi.149", value: "100MYR", display: "1490", vat: '6' },
        { name: "coda.mys_digi.299", value: "200MYR", display: "2990", vat: '6' },
    ],
    'coda.idn_smartfren': [
        { name: "coda.idn_smartfren.2", value: "5,000IDR", display: "20", vat: '10' },
        { name: "coda.idn_smartfren.21", value: "50,000IDR", display: "210", vat: '10' },
        { name: "coda.idn_smartfren.42", value: "100,000IDR", display: "420", vat: '10' },
        { name: "coda.idn_smartfren.106", value: "250,000IDR", display: "1060", vat: '10' },
        { name: "coda.idn_smartfren.212", value: "500,000IDR", display: "2120", vat: '10' },
        { name: "coda.idn_smartfren.425", value: "1,000,000IDR", display: "4250", vat: '10' },
        { name: "coda.idn_smartfren.850", value: "2,000,000IDR", display: "8500", vat: '10' },
        { name: "coda.idn_smartfren.2127", value: "5,000,000IDR", display: "21270", vat: '10' },
    ],
    'coda.idn_telkomsel': [
        { name: "coda.idn_telkomsel.2", value: "5,000IDR", display: "20", vat: '10' },
        { name: "coda.idn_telkomsel.8", value: "20,000IDR", display: "80", vat: '10' },
        { name: "coda.idn_telkomsel.21", value: "50,000IDR", display: "210", vat: '10' },
        { name: "coda.idn_telkomsel.42", value: "100,000IDR", display: "420", vat: '10' },
        { name: "coda.idn_telkomsel.106", value: "250,000IDR", display: "1060", vat: '10' },
        { name: "coda.idn_telkomsel.212", value: "500,000IDR", display: "2120", vat: '10' },
    ],
    'coda.idn_indosat': [
        { name: "coda.idn_indosat.2", value: "5,000IDR", display: "20", vat: '10' },
        { name: "coda.idn_indosat.8", value: "20,000IDR", display: "80", vat: '10' },
        { name: "coda.idn_indosat.21", value: "50,000IDR", display: "210", vat: '10' },
        { name: "coda.idn_indosat.42", value: "100,000IDR", display: "420", vat: '10' },
        { name: "coda.idn_indosat.106", value: "250,000IDR", display: "1060", vat: '10' },
        { name: "coda.idn_indosat.212", value: "500,000IDR", display: "2120", vat: '10' },
        { name: "coda.idn_indosat.425", value: "1,000,000IDR", display: "4250", vat: '10' },
    ],
    'coda.idn_xl': [
        { name: "coda.idn_xl.2", value: "5,000IDR", display: "20", vat: '10' },
        { name: "coda.idn_xl.8", value: "20,000IDR", display: "80", vat: '10' },
        { name: "coda.idn_xl.21", value: "50,000IDR", display: "210", vat: '10' },
        { name: "coda.idn_xl.42", value: "100,000IDR", display: "420", vat: '10' },
        { name: "coda.idn_xl.106", value: "250,000IDR", display: "1060", vat: '10' },
        { name: "coda.idn_xl.212", value: "500,000IDR", display: "2120", vat: '10' },
        { name: "coda.idn_xl.425", value: "1,000,000IDR", display: "4250", vat: '10' },
    ],
    'coda.idn_3': [
        { name: "coda.idn_3.2", value: "6,000IDR", display: "20", vat: '10' },
        { name: "coda.idn_3.7", value: "20,000IDR", display: "70", vat: '10' },
        { name: "coda.idn_3.19", value: "50,000IDR", display: "190", vat: '10' },
        { name: "coda.idn_3.39", value: "100,000IDR", display: "390", vat: '10' },
        { name: "coda.idn_3.97", value: "250,000IDR", display: "970", vat: '10' },
        { name: "coda.idn_3.195", value: "500,000IDR", display: "1950", vat: '10' },
        { name: "coda.idn_3.390", value: "1,000,000IDR", display: "3900", vat: '10' },
    ],
    'coda.idn_bank': [
        { name: "coda.idn_bank.18", value: "50,000IDR", display: "180" },
        { name: "coda.idn_bank.49", value: "100,000IDR", display: "490" },
        { name: "coda.idn_bank.140", value: "250,000IDR", display: "1400" },
        { name: "coda.idn_bank.293", value: "500,000IDR", display: "2930" },
        { name: "coda.idn_bank.598", value: "1,000,000IDR", display: "5980" },
        { name: "coda.idn_bank.1208", value: "2,000,000IDR", display: "12080" },
        { name: "coda.idn_bank.3037", value: "5,000,000IDR", display: "30370" },
        { name: "coda.idn_bank.6087", value: "10,000,000IDR", display: "60870" },
    ],
    'coda.idn_gopay': [
        { name: "coda.idn_gopay.2", value: "5,000IDR", display: "20" },
        { name: "coda.idn_gopay.5", value: "10,000IDR", display: "50" },
        { name: "coda.idn_gopay.28", value: "50,000IDR", display: "280" },
        { name: "coda.idn_gopay.56", value: "100,000IDR", display: "560" },
        { name: "coda.idn_gopay.141", value: "250,000IDR", display: "1410" },
        { name: "coda.idn_gopay.567", value: "1,000,000IDR", display: "5670" },
        { name: "coda.idn_gopay.1134", value: "2,000,000IDR", display: "11340" },
        { name: "coda.idn_gopay.2836", value: "5,000,000IDR", display: "28360" },
        { name: "coda.idn_gopay.5673", value: "10,000,000IDR", display: "56730" },
    ],
    'coda.idn_alfamart': [
        { name: "coda.idn_alfamart.24", value: "50,000IDR", display: "240" },
        { name: "coda.idn_alfamart.54", value: "100,000IDR", display: "540" },
        { name: "coda.idn_alfamart.146", value: "250,000IDR", display: "1460" },
        { name: "coda.idn_alfamart.298", value: "500,000IDR", display: "2980" },
        { name: "coda.idn_alfamart.603", value: "1,000,000IDR", display: "6030" },
        { name: "coda.idn_alfamart.1213", value: "2,000,000IDR", display: "12130" },
    ],
    'coda.idn_doku': [
        { name: "coda.idn_doku.3", value: "5,000IDR", display: "30" },
        { name: "coda.idn_doku.6", value: "10,000IDR", display: "60" },
        { name: "coda.idn_doku.18", value: "30,000IDR", display: "180" },
        { name: "coda.idn_doku.30", value: "50,000IDR", display: "300" },
        { name: "coda.idn_doku.61", value: "100,000IDR", display: "610" },
        { name: "coda.idn_doku.153", value: "250,000IDR", display: "1530" },
        { name: "coda.idn_doku.306", value: "500,000IDR", display: "3060" },
        { name: "coda.idn_doku.613", value: "1,000,000IDR", display: "6130" },
        { name: "coda.idn_doku.1533", value: "2500,000IDR", display: "15330" },
        { name: "coda.idn_doku.3067", value: "5,000,000IDR", display: "30670" },
    ],
    'coda.tha_banktransfer': [
        { name: "coda.tha_banktransfer.5", value: "20THB", display: "50" },
        { name: "coda.tha_banktransfer.14", value: "50THB", display: "140" },
        { name: "coda.tha_banktransfer.29", value: "100THB", display: "290" },
        { name: "coda.tha_banktransfer.88", value: "300THB", display: "880" },
        { name: "coda.tha_banktransfer.146", value: "500THB", display: "1460" },
        { name: "coda.tha_banktransfer.293", value: "1000THB", display: "2930" },
        { name: "coda.tha_banktransfer.881", value: "3000THB", display: "8810" },
        { name: "coda.tha_banktransfer.1469", value: "5000THB", display: "14690" },
        { name: "coda.tha_banktransfer.2939", value: "10000THB", display: "29390" },
        { name: "coda.tha_banktransfer.5879", value: "20000THB", display: "58790" },
        { name: "coda.tha_banktransfer.8819", value: "30000THB", display: "88190" },
    ],
    'coda.tha_rabbit': [
        { name: "coda.tha_rabbit.5", value: "20THB", display: "50" },
        { name: "coda.tha_rabbit.14", value: "50THB", display: "140" },
        { name: "coda.tha_rabbit.28", value: "100THB", display: "280" },
        { name: "coda.tha_rabbit.84", value: "300THB", display: "840" },
        { name: "coda.tha_rabbit.140", value: "500THB", display: "1400" },
        { name: "coda.tha_rabbit.281", value: "1000THB", display: "2810" },
        { name: "coda.tha_rabbit.843", value: "3000THB", display: "8430" },
        { name: "coda.tha_rabbit.1406", value: "5000THB", display: "14060" },
        { name: "coda.tha_rabbit.2813", value: "10000THB", display: "28130" },
        { name: "coda.tha_rabbit.5626", value: "20000THB", display: "56260" },
    ],
    'coda.tha_truemw': [
        { name: "coda.tha_truemw.5", value: "20THB", display: "50" },
        { name: "coda.tha_truemw.14", value: "50THB", display: "140" },
        { name: "coda.tha_truemw.28", value: "100THB", display: "280" },
        { name: "coda.tha_truemw.84", value: "300THB", display: "840" },
        { name: "coda.tha_truemw.140", value: "500THB", display: "1400" },
        { name: "coda.tha_truemw.281", value: "1000THB", display: "2810" },
        { name: "coda.tha_truemw.843", value: "3000THB", display: "8430" },
        { name: "coda.tha_truemw.1406", value: "5000THB", display: "14060" },
        { name: "coda.tha_truemw.2813", value: "10000THB", display: "28130" },
        { name: "coda.tha_truemw.5626", value: "20000THB", display: "56260" },
    ],
    'coda.tha_dtac': [
        { name: "coda.tha_dtac.2", value: "10THB", display: "20" },
        { name: "coda.tha_dtac.4", value: "20THB", display: "40" },
        { name: "coda.tha_dtac.11", value: "50THB", display: "110" },
        { name: "coda.tha_dtac.22", value: "100THB", display: "220" },
        { name: "coda.tha_dtac.66", value: "300THB", display: "660" },
        { name: "coda.tha_dtac.110", value: "500THB", display: "1100" },
        { name: "coda.tha_dtac.221", value: "1000THB", display: "2210" },
        { name: "coda.tha_dtac.442", value: "2000THB", display: "4420" },
        { name: "coda.tha_dtac.663", value: "3000THB", display: "6630" },
    ],
    'coda.tha_ais': [
        { name: "coda.tha_ais.2", value: "10THB", display: "20" },
        { name: "coda.tha_ais.4", value: "20THB", display: "40" },
        { name: "coda.tha_ais.11", value: "50THB", display: "110" },
        { name: "coda.tha_ais.22", value: "100THB", display: "220" },
        { name: "coda.tha_ais.66", value: "300THB", display: "660" },
        { name: "coda.tha_ais.110", value: "500THB", display: "1100" },
    ],
    'coda.tha_cat': [
        { name: "coda.tha_cat.2", value: "10THB", display: "20" },
        { name: "coda.tha_cat.4", value: "20THB", display: "40" },
        { name: "coda.tha_cat.11", value: "50THB", display: "110" },
        { name: "coda.tha_cat.22", value: "100THB", display: "220" },
        { name: "coda.tha_cat.66", value: "300THB", display: "660" },
        { name: "coda.tha_cat.110", value: "500THB", display: "1100" },
        { name: "coda.tha_cat.221", value: "1000THB", display: "2210" },
        { name: "coda.tha_cat.442", value: "2000THB", display: "4420" },
    ],
    'coda.tha_truemove': [
        { name: "coda.tha_truemove.2", value: "10THB", display: "20" },
        { name: "coda.tha_truemove.4", value: "20THB", display: "40" },
        { name: "coda.tha_truemove.11", value: "50THB", display: "110" },
        { name: "coda.tha_truemove.22", value: "100THB", display: "220" },
        { name: "coda.tha_truemove.66", value: "300THB", display: "660" },
        { name: "coda.tha_truemove.110", value: "500THB", display: "1100" },
    ],
    'coda.are_etisalat': [
        { name: "coda.are_etisalat.3", value: "2AED", display: "30", vat: '5' },
        { name: "coda.are_etisalat.8", value: "5AED", display: "80", vat: '5' },
        { name: "coda.are_etisalat.17", value: "10AED", display: "170", vat: '5' },
        { name: "coda.are_etisalat.34", value: "20AED", display: "340", vat: '5' },
        { name: "coda.are_etisalat.68", value: "40AED", display: "680", vat: '5' },
    ],
    'coda.kwt_zain': [
        { name: "coda.kwt_zain.21", value: "1KWD", display: "210" },
        { name: "coda.kwt_zain.42", value: "2KWD", display: "420" },
        { name: "coda.kwt_zain.105", value: "5KWD", display: "1050" },
        { name: "coda.kwt_zain.211", value: "10KWD", display: "2110" },
        { name: "coda.kwt_zain.317", value: "15KWD", display: "3170" },
        { name: "coda.kwt_zain.423", value: "20KWD", display: "4230" },
    ],
    'coda.bhr_zain': [
        { name: "coda.bhr_zain.16", value: "1BHD", display: "160", vat: '5' },
        { name: "coda.bhr_zain.33", value: "2BHD", display: "330", vat: '5' },
        { name: "coda.bhr_zain.83", value: "5BHD", display: "830", vat: '5' },
        { name: "coda.bhr_zain.167", value: "10BHD", display: "1670", vat: '5' },
        { name: "coda.bhr_zain.334", value: "20BHD", display: "3340", vat: '5' },
        { name: "coda.bhr_zain.501", value: "30BHD", display: "5010", vat: '5' },
    ],
    'upay.bank': [
        { name: "upay.vnm_bank.18", value: "50,000VND", display: "180", vat: '10' },
        { name: "upay.vnm_bank.36", value: "100,000VND", display: "360", vat: '10' },
        { name: "upay.vnm_bank.73", value: "200,000VND", display: "730", vat: '10' },
        { name: "upay.vnm_bank.182", value: "500,000VND", display: "1820", vat: '10' },
        { name: "upay.vnm_bank.365", value: "1,000,000VND", display: "3650", vat: '10' },
        { name: "upay.vnm_bank.1827", value: "5,000,000VND", display: "18270", vat: '10' },
        { name: "upay.vnm_bank.3654", value: "10,000,000VND", display: "36540", vat: '10' },
    ],
    'upay.momo': [
        { name: "upay.vnm_momo.18", value: "50,000VND", display: "180", vat: '10' },
        { name: "upay.vnm_momo.36", value: "100,000VND", display: "360", vat: '10' },
        { name: "upay.vnm_momo.73", value: "200,000VND", display: "730", vat: '10' },
        { name: "upay.vnm_momo.182", value: "500,000VND", display: "1820", vat: '10' },
        { name: "upay.vnm_momo.365", value: "1,000,000VND", display: "3650", vat: '10' },
        { name: "upay.vnm_momo.1827", value: "5,000,000VND", display: "18270", vat: '10' },
        { name: "upay.vnm_momo.3654", value: "10,000,000VND", display: "36540", vat: '10' },
    ],
    'upay.card.vnp': [
        { name: "upay.vnm_xxx.0", value: "10,000VND", display: "20", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "20,000VND", display: "40", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "30,000VND", display: "70", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "50,000VND", display: "120", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "100,000VND", display: "240", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "200,000VND", display: "490", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "300,000VND", display: "740", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "500,000VND", display: "1240", vat: '10' },
    ],
    'upay.card.vtt': [
        { name: "upay.vnm_xxx.0", value: "10,000VND", display: "20", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "20,000VND", display: "40", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "30,000VND", display: "70", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "50,000VND", display: "120", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "100,000VND", display: "240", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "200,000VND", display: "490", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "300,000VND", display: "740", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "500,000VND", display: "1240", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "1,000,000VND", display: "2490", vat: '10' },
    ],
    'upay.card.vms': [
        { name: "upay.vnm_xxx.0", value: "50,000VND", display: "120", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "100,000VND", display: "240", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "200,000VND", display: "490", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "300,000VND", display: "740", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "500,000VND", display: "1240", vat: '10' },
    ],
    'upay.card.zing': [
        { name: "upay.vnm_xxx.0", value: "10,000VND", display: "20", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "20,000VND", display: "50", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "50,000VND", display: "130", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "100,000VND", display: "270", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "200,000VND", display: "550", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "500,000VND", display: "1390", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "1,000,000VND", display: "2790", vat: '10' },
    ],
    'upay.card.fpt': [
        { name: "upay.vnm_xxx.0", value: "10,000VND", display: "20", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "20,000VND", display: "50", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "50,000VND", display: "130", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "100,000VND", display: "270", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "200,000VND", display: "550", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "500,000VND", display: "1390", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "1,000,000VND", display: "2790", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "2,000,000VND", display: "5580", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "5,000,000VND", display: "13970", vat: '10' },
        { name: "upay.vnm_xxx.0", value: "10,000,000VND", display: "27940", vat: '10' },
    ],
    'razer.twn.wallet': [
        { name: "razer.twn_wallet.7", value: "30TWD", display: "70" },
        { name: "razer.twn_wallet.12", value: "50TWD", display: "120" },
        { name: "razer.twn_wallet.24", value: "100TWD", display: "240" },
        { name: "razer.twn_wallet.48", value: "200TWD", display: "480" },
        { name: "razer.twn_wallet.120", value: "500TWD", display: "1200" },
        { name: "razer.twn_wallet.241", value: "1000TWD", display: "2410" },
        { name: "razer.twn_wallet.483", value: "2000TWD", display: "4830" },
        { name: "razer.twn_wallet.1208", value: "5000TWD", display: "12080" },
        { name: "razer.twn_wallet.1933", value: "8000TWD", display: "19330" },
    ],
    'razer.twn.pin': [
        { name: "razer.xxx_pin.0", value: "50TWD", display: "110" },
        { name: "razer.xxx_pin.0", value: "100TWD", display: "230" },
        { name: "razer.xxx_pin.0", value: "300TWD", display: "690" },
        { name: "razer.xxx_pin.0", value: "500TWD", display: "1150" },
        { name: "razer.xxx_pin.0", value: "1000TWD", display: "2300" },
        { name: "razer.xxx_pin.0", value: "2000TWD", display: "4600" },
    ],
    'razer.hkg.wallet': [
        { name: "razer.hkg_wallet.9", value: "10HKD", display: "90" },
        { name: "razer.hkg_wallet.18", value: "20HKD", display: "180" },
        { name: "razer.hkg_wallet.47", value: "50HKD", display: "470" },
        { name: "razer.hkg_wallet.94", value: "100HKD", display: "940" },
        { name: "razer.hkg_wallet.188", value: "200HKD", display: "1880" },
        { name: "razer.hkg_wallet.470", value: "500HKD", display: "4700" },
        { name: "razer.hkg_wallet.941", value: "1000HKD", display: "9410" },
        { name: "razer.hkg_wallet.1883", value: "2000HKD", display: "18830" },
    ],
    'razer.hkg.pin': [
        { name: "razer.xxx_pin.0", value: "50HKD", display: "470" },
        { name: "razer.xxx_pin.0", value: "88HKD", display: "820" },
        { name: "razer.xxx_pin.0", value: "100HKD", display: "940" },
        { name: "razer.xxx_pin.0", value: "200HKD", display: "1880" },
        { name: "razer.xxx_pin.0", value: "248HKD", display: "2330" },
        { name: "razer.xxx_pin.0", value: "300HKD", display: "2820" },
        { name: "razer.xxx_pin.0", value: "398HKD", display: "3740" },
        { name: "razer.xxx_pin.0", value: "400HKD", display: "3760" },
        { name: "razer.xxx_pin.0", value: "500HKD", display: "4700" },
        { name: "razer.xxx_pin.0", value: "788HKD", display: "7420" },
    ],
    'razer.sgp.pin': [
        { name: "razer.xxx_pin.0", value: "10SGD", display: "510" },
        { name: "razer.xxx_pin.0", value: "11SGD", display: "560" },
        { name: "razer.xxx_pin.0", value: "20SGD", display: "1020" },
        { name: "razer.xxx_pin.0", value: "30SGD", display: "1530" },
        { name: "razer.xxx_pin.0", value: "50SGD", display: "2560" },
        { name: "razer.xxx_pin.0", value: "60SGD", display: "3070" },
        { name: "razer.xxx_pin.0", value: "80SGD", display: "4090" },
        { name: "razer.xxx_pin.0", value: "100SGD", display: "5120" },
        { name: "razer.xxx_pin.0", value: "125SGD", display: "6400" },
        { name: "razer.xxx_pin.0", value: "150SGD", display: "7680" },
        { name: "razer.xxx_pin.0", value: "200SGD", display: "10240" },
        { name: "razer.xxx_pin.0", value: "300SGD", display: "15370" },
    ],
    'razer.mys.fpx': [
        { name: "razer.mys_fpx.18", value: "10MYR", display: "180" },
        { name: "razer.mys_fpx.36", value: "20MYR", display: "360" },
        { name: "razer.mys_fpx.90", value: "50MYR", display: "900" },
        { name: "razer.mys_fpx.180", value: "100MYR", display: "1800" },
        { name: "razer.mys_fpx.361", value: "200MYR", display: "3610" },
        { name: "razer.mys_fpx.903", value: "500MYR", display: "9030" },
        { name: "razer.mys_fpx.1806", value: "1000MYR", display: "18060" },
        { name: "razer.mys_fpx.5420", value: "3000MYR", display: "54200" },
        { name: "razer.mys_fpx.9033", value: "5000MYR", display: "90330" },
    ],
    'razer.mys.wallet': [
        { name: "razer.mys_wallet.3", value: "2MYR", display: "30" },
        { name: "razer.mys_wallet.18", value: "10MYR", display: "180" },
        { name: "razer.mys_wallet.36", value: "20MYR", display: "360" },
        { name: "razer.mys_wallet.90", value: "50MYR", display: "900" },
        { name: "razer.mys_wallet.180", value: "100MYR", display: "1800" },
        { name: "razer.mys_wallet.361", value: "200MYR", display: "3610" },
        { name: "razer.mys_wallet.903", value: "500MYR", display: "9030" },
        { name: "razer.mys_wallet.1806", value: "1000MYR", display: "18060" },
        { name: "razer.mys_wallet.3613", value: "2000MYR", display: "36130" },
        { name: "razer.mys_wallet.5420", value: "3000MYR", display: "54200" },
    ],
    'razer.mys.pin': [
        { name: "razer.xxx_pin.0", value: "3MYR", display: "50" },
        { name: "razer.xxx_pin.0", value: "5MYR", display: "90" },
        { name: "razer.xxx_pin.0", value: "7MYR", display: "120" },
        { name: "razer.xxx_pin.0", value: "10MYR", display: "180" },
        { name: "razer.xxx_pin.0", value: "20MYR", display: "360" },
        { name: "razer.xxx_pin.0", value: "30MYR", display: "540" },
        { name: "razer.xxx_pin.0", value: "40MYR", display: "720" },
        { name: "razer.xxx_pin.0", value: "50MYR", display: "900" },
        { name: "razer.xxx_pin.0", value: "100MYR", display: "1800" },
        { name: "razer.xxx_pin.0", value: "150MYR", display: "2710" },
        { name: "razer.xxx_pin.0", value: "200MYR", display: "3610" },
        { name: "razer.xxx_pin.0", value: "300MYR", display: "5420" },
        { name: "razer.xxx_pin.0", value: "500MYR", display: "9030" },
        { name: "razer.xxx_pin.0", value: "1000MYR", display: "18060" },
        { name: "razer.xxx_pin.0", value: "2000MYR", display: "36130" },
        { name: "razer.xxx_pin.0", value: "3000MYR", display: "54200" },
    ],
    'razer.idn.wallet': [
        { name: "razer.idn_wallet.2", value: "5000IDR", display: "20" },
        { name: "razer.idn_wallet.5", value: "10000IDR", display: "50" },
        { name: "razer.idn_wallet.25", value: "50000IDR", display: "250" },
        { name: "razer.idn_wallet.51", value: "100000IDR", display: "510" },
        { name: "razer.idn_wallet.129", value: "250000IDR", display: "1290" },
        { name: "razer.idn_wallet.518", value: "1000000IDR", display: "5180" },
        { name: "razer.idn_wallet.1036", value: "2000000IDR", display: "10360" },
        { name: "razer.idn_wallet.2592", value: "5000000IDR", display: "25920" },
        { name: "razer.idn_wallet.5184", value: "10000000IDR", display: "51840" },
    ],
    'razer.idn.pin': [
        { name: "razer.xxx_pin.0", value: "10000IDR", display: "50" },
        { name: "razer.xxx_pin.0", value: "20000IDR", display: "100" },
        { name: "razer.xxx_pin.0", value: "50000IDR", display: "250" },
        { name: "razer.xxx_pin.0", value: "100000IDR", display: "510" },
        { name: "razer.xxx_pin.0", value: "200000IDR", display: "1030" },
        { name: "razer.xxx_pin.0", value: "500000IDR", display: "2590" },
        { name: "razer.xxx_pin.0", value: "1000000IDR", display: "5180" },
    ],
    'razer.tha.truemoney': [
        { name: "razer.tha_truemoney.12", value: "50THB", display: "120" },
        { name: "razer.tha_truemoney.22", value: "90THB", display: "220" },
        { name: "razer.tha_truemoney.37", value: "150THB", display: "370" },
        { name: "razer.tha_truemoney.74", value: "300THB", display: "740" },
        { name: "razer.tha_truemoney.124", value: "500THB", display: "1240" },
        { name: "razer.tha_truemoney.249", value: "1000THB", display: "2490" },
    ],
    'razer.tha.one2call': [
        { name: "razer.tha_one2call.12", value: "50THB", display: "120" },
        { name: "razer.tha_one2call.24", value: "100THB", display: "240" },
        { name: "razer.tha_one2call.74", value: "300THB", display: "740" },
        { name: "razer.tha_one2call.124", value: "500THB", display: "1240" },
        { name: "razer.tha_one2call.249", value: "1000THB", display: "2490" },
    ],
    'razer.tha.wallet': [
        { name: "razer.tha_wallet.5", value: "20THB", display: "50" },
        { name: "razer.tha_wallet.13", value: "50THB", display: "130" },
        { name: "razer.tha_wallet.26", value: "100THB", display: "260" },
        { name: "razer.tha_wallet.79", value: "300THB", display: "790" },
        { name: "razer.tha_wallet.133", value: "500THB", display: "1330" },
        { name: "razer.tha_wallet.266", value: "1000THB", display: "2660" },
        { name: "razer.tha_wallet.799", value: "3000THB", display: "7990" },
        { name: "razer.tha_wallet.1333", value: "5000THB", display: "13330" },
        { name: "razer.tha_wallet.2666", value: "10000THB", display: "26660" },
        { name: "razer.tha_wallet.5332", value: "20000THB", display: "53320" },
    ],
    'razer.tha.pin': [
        { name: "razer.xxx_pin.0", value: "50THB", display: "120" },
        { name: "razer.xxx_pin.0", value: "100THB", display: "240" },
        { name: "razer.xxx_pin.0", value: "300THB", display: "740" },
        { name: "razer.xxx_pin.0", value: "500THB", display: "1240" },
        { name: "razer.xxx_pin.0", value: "1000THB", display: "2490" },
        { name: "razer.xxx_pin.0", value: "3500THB", display: "8740" },
        { name: "razer.xxx_pin.0", value: "5000THB", display: "12490" },
    ],
    'razer.vnm.wallet': [
        { name: "razer.vnm_wallet.2", value: "10000VND", display: "20" },
        { name: "razer.vnm_wallet.5", value: "20000VND", display: "50" },
        { name: "razer.vnm_wallet.14", value: "50000VND", display: "140" },
        { name: "razer.vnm_wallet.29", value: "100000VND", display: "290" },
        { name: "razer.vnm_wallet.58", value: "200000VND", display: "580" },
        { name: "razer.vnm_wallet.147", value: "500000VND", display: "1470" },
        { name: "razer.vnm_wallet.294", value: "1000000VND", display: "2940" },
        { name: "razer.vnm_wallet.1470", value: "5000000VND", display: "14700" },
        { name: "razer.vnm_wallet.2941", value: "10000000VND", display: "29410" },
    ],
    'razer.vnm.pin': [
        { name: "razer.xxx_pin.0", value: "10000VND", display: "20" },
        { name: "razer.xxx_pin.0", value: "20000VND", display: "50" },
        { name: "razer.xxx_pin.0", value: "30000VND", display: "70" },
        { name: "razer.xxx_pin.0", value: "50000VND", display: "130" },
        { name: "razer.xxx_pin.0", value: "100000VND", display: "260" },
        { name: "razer.xxx_pin.0", value: "200000VND", display: "520" },
        { name: "razer.xxx_pin.0", value: "300000VND", display: "780" },
        { name: "razer.xxx_pin.0", value: "500000VND", display: "1310" },
    ],
    'razer.sau.wallet': [
        { name: "razer.sau_wallet.7", value: "1USD", display: "70" },
        { name: "razer.sau_wallet.14", value: "2USD", display: "140" },
        { name: "razer.sau_wallet.36", value: "5USD", display: "360" },
        { name: "razer.sau_wallet.73", value: "10USD", display: "730" },
        { name: "razer.sau_wallet.146", value: "20USD", display: "1460" },
        { name: "razer.sau_wallet.365", value: "50USD", display: "3650" },
        { name: "razer.sau_wallet.730", value: "100USD", display: "7300" },
        { name: "razer.sau_wallet.1460", value: "200USD", display: "14600" },
        { name: "razer.sau_wallet.3650", value: "500USD", display: "36500" },
    ],
    'razer.usa.pin': [
        { name: "razer.xxx_pin.0", value: "1USD", display: "70" },
        { name: "razer.xxx_pin.0", value: "2USD", display: "140" },
        { name: "razer.xxx_pin.0", value: "5USD", display: "360" },
        { name: "razer.xxx_pin.0", value: "10USD", display: "730" },
        { name: "razer.xxx_pin.0", value: "20USD", display: "1460" },
        { name: "razer.xxx_pin.0", value: "50USD", display: "3650" },
        { name: "razer.xxx_pin.0", value: "100USD", display: "7300" },
    ],
    'razer.us.pin': [
        { name: "razer.xxx_pin.0", value: "5USD", display: "400" },
        { name: "razer.xxx_pin.0", value: "10USD", display: "800" },
        { name: "razer.xxx_pin.0", value: "20USD", display: "1600" },
        { name: "razer.xxx_pin.0", value: "25USD", display: "2000" },
        { name: "razer.xxx_pin.0", value: "50USD", display: "4000" },
        { name: "razer.xxx_pin.0", value: "100USD", display: "8000" },
    ],
    'razer.nzl.pin': [
        { name: "razer.xxx_pin.0", value: "5NZD", display: "240" },
        { name: "razer.xxx_pin.0", value: "10NZD", display: "480" },
        { name: "razer.xxx_pin.0", value: "20NZD", display: "970" },
        { name: "razer.xxx_pin.0", value: "50NZD", display: "2420" },
        { name: "razer.xxx_pin.0", value: "100NZD", display: "4850" },
    ],
    'razer.bra.pin': [
        { name: "razer.xxx_pin.0", value: "5BRL", display: "60" },
        { name: "razer.xxx_pin.0", value: "10BRL", display: "130" },
        { name: "razer.xxx_pin.0", value: "20BRL", display: "270" },
        { name: "razer.xxx_pin.0", value: "25BRL", display: "340" },
        { name: "razer.xxx_pin.0", value: "28BRL", display: "390" },
        { name: "razer.xxx_pin.0", value: "30BRL", display: "410" },
        { name: "razer.xxx_pin.0", value: "31BRL", display: "430" },
        { name: "razer.xxx_pin.0", value: "50BRL", display: "690" },
        { name: "razer.xxx_pin.0", value: "52BRL", display: "720" },
        { name: "razer.xxx_pin.0", value: "75BRL", display: "1040" },
        { name: "razer.xxx_pin.0", value: "100BRL", display: "1390" },
        { name: "razer.xxx_pin.0", value: "150BRL", display: "2090" },
        { name: "razer.xxx_pin.0", value: "200BRL", display: "2880" },
    ],
    'razer.aus.pin': [
        { name: "razer.xxx_pin.0", value: "5AUD", display: "250" },
        { name: "razer.xxx_pin.0", value: "10AUD", display: "510" },
        { name: "razer.xxx_pin.0", value: "20AUD", display: "1030" },
        { name: "razer.xxx_pin.0", value: "50AUD", display: "2580" },
        { name: "razer.xxx_pin.0", value: "100AUD", display: "5160" },
    ],
    'razer.phl.pin': [
        { name: "razer.xxx_pin.0", value: "20PHP", display: "30" },
        { name: "razer.xxx_pin.0", value: "50PHP", display: "70" },
        { name: "razer.xxx_pin.0", value: "100PHP", display: "150" },
        { name: "razer.xxx_pin.0", value: "150PHP", display: "220" },
        { name: "razer.xxx_pin.0", value: "200PHP", display: "300" },
        { name: "razer.xxx_pin.0", value: "250PHP", display: "370" },
        { name: "razer.xxx_pin.0", value: "300PHP", display: "450" },
        { name: "razer.xxx_pin.0", value: "500PHP", display: "750" },
        { name: "razer.xxx_pin.0", value: "1000PHP", display: "1510" },
        { name: "razer.xxx_pin.0", value: "2000PHP", display: "3030" },
        { name: "razer.xxx_pin.0", value: "5000PHP", display: "7590" },
    ],
    'razer.ind.pin': [
        { name: "razer.xxx_pin.0", value: "50INR", display: "40" },
        { name: "razer.xxx_pin.0", value: "100INR", display: "90" },
        { name: "razer.xxx_pin.0", value: "250INR", display: "240" },
        { name: "razer.xxx_pin.0", value: "500INR", display: "490" },
        { name: "razer.xxx_pin.0", value: "1000INR", display: "990" },
        { name: "razer.xxx_pin.0", value: "2000INR", display: "1980" },
        { name: "razer.xxx_pin.0", value: "2500INR", display: "2480" },
        { name: "razer.xxx_pin.0", value: "3000INR", display: "2970" },
        { name: "razer.xxx_pin.0", value: "5000INR", display: "4960" },
    ],
    'razer.eur.pin': [
        { name: "razer.xxx_pin.0", value: "5EUR", display: "470" },
        { name: "razer.xxx_pin.0", value: "10EUR", display: "950" },
        { name: "razer.xxx_pin.0", value: "20EUR", display: "1900" },
        { name: "razer.xxx_pin.0", value: "50EUR", display: "4750" },
        { name: "razer.xxx_pin.0", value: "100EUR", display: "9500" },
    ],
    'razer.mmr.pin': [ //緬甸
        { name: "razer.xxx_pin.0", value: "500MMK", display: "20" },
        { name: "razer.xxx_pin.0", value: "1000MMK", display: "50" },
        { name: "razer.xxx_pin.0", value: "3000MMK", display: "170" },
        { name: "razer.xxx_pin.0", value: "5000MMK", display: "290" },
        { name: "razer.xxx_pin.0", value: "10000MMK", display: "590" },
        { name: "razer.xxx_pin.0", value: "20000MMK", display: "1180" },
    ],
    'razer.tur.pin': [ //土耳其
        { name: "razer.xxx_pin.0", value: "2TRY", display: "10" },
        { name: "razer.xxx_pin.0", value: "5TRY", display: "40" },
        { name: "razer.xxx_pin.0", value: "10TRY", display: "90" },
        { name: "razer.xxx_pin.0", value: "15TRY", display: "140" },
        { name: "razer.xxx_pin.0", value: "25TRY", display: "230" },
        { name: "razer.xxx_pin.0", value: "50TRY", display: "460" },
        { name: "razer.xxx_pin.0", value: "100TRY", display: "930" },
        { name: "razer.xxx_pin.0", value: "250TRY", display: "2340" },
        { name: "razer.xxx_pin.0", value: "500TRY", display: "4680" },
    ],
    'razer.mex.pin': [ //墨西哥
        { name: "razer.xxx_pin.0", value: "100MXN", display: "360" },
        { name: "razer.xxx_pin.0", value: "150MXN", display: "550" },
        { name: "razer.xxx_pin.0", value: "200MXN", display: "730" },
        { name: "razer.xxx_pin.0", value: "300MXN", display: "1100" },
        { name: "razer.xxx_pin.0", value: "350MXN", display: "1280" },
        { name: "razer.xxx_pin.0", value: "500MXN", display: "1830" },
        { name: "razer.xxx_pin.0", value: "600MXN", display: "2200" },
        { name: "razer.xxx_pin.0", value: "1000MXN", display: "3670" },
    ],
    'razer.can.pin': [
        { name: "razer.xxx_pin.0", value: "10CAD", display: "560" },
        { name: "razer.xxx_pin.0", value: "20CAD", display: "1130" },
        { name: "razer.xxx_pin.0", value: "25CAD", display: "1420" },
        { name: "razer.xxx_pin.0", value: "50CAD", display: "2840" },
        { name: "razer.xxx_pin.0", value: "100CAD", display: "5690" },
    ],
    'mentwall.kor.card': [
        { name: "mentwall.kor_card.4", value: "500KRW", display: "40" },
    ],
    'adyen.any.card': [
        { name: "adyen.any_card.56", value: "6USD", display: "560" },
        { name: "adyen.any_card.84", value: "9USD", display: "840" },
        { name: "adyen.any_card.178", value: "19USD", display: "1780" },
        { name: "adyen.any_card.366", value: "39USD", display: "3660" },
        { name: "adyen.any_card.554", value: "59USD", display: "5540" },
        { name: "adyen.any_card.836", value: "89USD", display: "8360" },
        { name: "adyen.any_card.1306", value: "139USD", display: "13060" },
        { name: "adyen.any_card.1870", value: "199USD", display: "18700" },
        { name: "adyen.any_card.2528", value: "269USD", display: "25280" },
        { name: "adyen.any_card.4314", value: "459USD", display: "43140" },
    ],
    'adyen.any.amex': [
        { name: "adyen.any_amex.31", value: "5SGD", display: "310" },
        { name: "adyen.any_amex.66", value: "10SGD", display: "660" },
        { name: "adyen.any_amex.134", value: "20SGD", display: "1340" },
        { name: "adyen.any_amex.340", value: "50SGD", display: "3400" },
        { name: "adyen.any_amex.546", value: "80SGD", display: "5460" },
        { name: "adyen.any_amex.683", value: "100SGD", display: "6830" },
        { name: "adyen.any_amex.1369", value: "200SGD", display: "13690" },
        { name: "adyen.any_amex.3426", value: "500SGD", display: "34260" }
    ]
};


// 分地区支付通道
export const areas = [
    {
        area: '中國大陸',
        areaNum: 1,
        alpha: 'CHN',
        remote: true,
        data: []
    },
    {
        area: '臺灣',
        areaNum: 2,
        alpha: 'TWN',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: '信用卡/借記卡', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.twn.wallet", channel: "", platform: "razer", platformName: 'Razer Gold Wallet', data: products['razer.twn.wallet'] },
            { id: "razer.twn.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.twn.pin'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: '支付寶', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: '借記卡/信用卡', data: products['fomo.card'] },
            // { id: "p99.TELCHT05", channel: "TELCHT05", platform: "p99", platformName: '中華電信 手機 839(三合一)', data: products['p99.tel'] },
            // { id: "p99.TELCHT06", channel: "TELCHT06", platform: "p99", platformName: '中華電信 Hinet(三合一)', data: products['p99.tel'] },
            // { id: "p99.TELFET01", channel: "TELFET01", platform: "p99", platformName: '遠傳電信一般型', data: products['p99.tel'] },
            // { id: "p99.TELSON04", channel: "TELSON04", platform: "p99", platformName: '亞太電信手機', data: products['p99.tel'] },
            // { id: "p99.TELTCC01", channel: "TELTCC01", platform: "p99", platformName: '台灣大哥大一般型', data: products['p99.tel'] },
            { id: "p99.BNK80801", channel: "BNK80801", platform: "p99", platformName: '玉山銀行WEB ATM', data: products['p99.card'] },
            { id: "p99.BNK82201", channel: "BNK82201", platform: "p99", platformName: 'VISA/MasterCard/JCB 信用卡', data: products['p99.card'] },
        ]
    },
    {
        area: '香港',
        areaNum: 3,
        alpha: 'HKG',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: '信用卡/借記卡', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.hkg.wallet", channel: "", platform: "razer", platformName: 'Razer Gold Wallet', data: products['razer.hkg.wallet'] },
            { id: "razer.hkg.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.hkg.pin'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: '支付寶', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: '借記卡/信用卡', data: products['fomo.card'] },
            { id: "p99.BNK80801", channel: "BNK80801", platform: "p99", platformName: '玉山銀行WEB ATM', data: products['p99.card'] },
            { id: "p99.BNK82201", channel: "BNK82201", platform: "p99", platformName: 'VISA/MasterCard/JCB 信用卡', data: products['p99.card'] },
        ]
    },
    {
        area: '新加坡(Singapore)',
        areaNum: 4,
        alpha: 'SGP',
        remote: true,
        data: [
            // { id: "fomo.alisgp", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.alisgp'] },
            // { id: "fomo.cardsgp", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.cardsgp'] },
        ]
    },
    {
        area: '馬來西亞(Malaysia)',
        areaNum: 5,
        alpha: 'MYS',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            //razer.mys.wallet
            { id: "razer.mys_wallet", channel: "", platform: "razer", platformName: "Razer Gold Wallet", data: products['razer.mys.wallet'] },
            { id: "razer.mys_pin", channel: "", platform: "razer", platformName: "Razer Gold Pin", data: products['razer.mys.pin'] },
            //{ id: "coda.mys_fpx", channel: "", platform: "razer", platformName: "Fpx", data: products['coda.mys.fpx'] },
            { id: "coda.mys_touchgo", channel: "", platform: "coda", platformName: "Touch'n Go", data: products['coda.mys_touchgo'] },
            // { id: "coda.mys_grabpay", channel: "", platform: "coda", platformName: "Grabpay", data: products['coda.mys_grabpay'] },
            { id: "coda.mys_boostewallet", channel: "", platform: "coda", platformName: "Boost eWallet", data: products['coda.mys_boostewallet'] },
            { id: "coda.mys_celcom", channel: "", platform: "coda", platformName: "Celcom", data: products['coda.mys_celcom'] },
            { id: "coda.mys_umobile", channel: "", platform: "coda", platformName: "U Mobile", data: products['coda.mys_umobile'] },
            { id: "coda.mys_maxis", channel: "", platform: "coda", platformName: "Maxis", data: products['coda.mys_maxis'] },
            { id: "coda.mys_digi", channel: "", platform: "coda", platformName: "Digi", data: products['coda.mys_digi'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
            // { id: "paypal.card", channel: "card", platform: "paypal", platformName: 'Paypal', data: products['paypal'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
        ]
    },
    {
        area: '韓國(한국)',
        areaNum: 6,
        alpha: 'KOR',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] }
        ]
    },
    {
        area: '印度尼西亞(Indonesia)',
        areaNum: 7,
        alpha: 'IDN',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.idn_wallet", channel: "", platform: "razer", platformName: "Razer Gold Wallet", data: products['razer.idn.wallet'] },
            { id: "razer.idn_pin", channel: "", platform: "razer", platformName: "Razer Gold Pin", data: products['razer.idn.pin'] },
            // { id: "coda.idn_smartfren", channel: "", platform: "coda", platformName: "Smartfren", data: products['coda.idn_smartfren'] },
            // { id: "coda.idn_bank", channel: "", platform: "coda", platformName: "bank transfer", data: products['coda.idn_bank'] },
            // { id: "coda.idn_gopay", channel: "", platform: "coda", platformName: "GO-PAY", data: products['coda.idn_gopay'] },
            // { id: "coda.idn_telkomsel", channel: "", platform: "coda", platformName: "Telkomsel", data: products['coda.idn_telkomsel'] },
            // { id: "coda.idn_indosat", channel: "", platform: "coda", platformName: "Indosat", data: products['coda.idn_indosat'] },
            // { id: "coda.idn_xl", channel: "", platform: "coda", platformName: "XL", data: products['coda.idn_xl'] },
            // { id: "coda.idn_3", channel: "", platform: "coda", platformName: "3", data: products['coda.idn_3'] },
            // { id: "coda.idn_alfamart", channel: "", platform: "coda", platformName: "Alfamart", data: products['coda.idn_alfamart'] },
            // { id: "coda.idn_doku", channel: "", platform: "coda", platformName: "Doku Wallet", data: products['coda.idn_doku'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
            // { id: "paypal.card", channel: "card", platform: "paypal", platformName: 'Paypal', data: products['paypal'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
        ]
    },
    {
        area: '泰國(ประเทศไทย)',
        areaNum: 8,
        alpha: 'THA',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.tha_wallet", channel: "", platform: "razer", platformName: "Razer Gold Wallet", data: products['razer.tha.wallet'] },
            { id: "razer.tha_pin", channel: "", platform: "razer", platformName: "Razer Gold Pin", data: products['razer.tha.pin'] },
            //{ id: "coda.tha_truemoney", channel: "", platform: "razer", platformName: "TrueMoney", data: products['razer.tha.truemoney'] },
            //{ id: "coda.tha_one2call", channel: "", platform: "razer", platformName: "One-2-Call", data: products['razer.tha.one2call'] },
            // { id: "coda.tha_pin", channel: "", platform: "razer", platformName: "Razer Gold Pin", data: products['razer.tha.pin'] },
            // { id: "coda.tha_dtac", channel: "", platform: "coda", platformName: "DTAC", data: products['coda.tha_dtac'] },
            // { id: "coda.tha_ais", channel: "", platform: "coda", platformName: "AIS", data: products['coda.tha_ais'] },
            // { id: "coda.tha_cat", channel: "", platform: "coda", platformName: 'CAT', data: products['coda.tha_cat'] },
            // { id: "coda.tha_truemove", channel: "", platform: "coda", platformName: 'Truemove TH', data: products['coda.tha_truemove'] },
            // { id: "coda.tha_truemw", channel: "", platform: "coda", platformName: "True Money Wallet", data: products['coda.tha_truemw'] },
            // { id: "coda.tha_rabbit", channel: "", platform: "coda", platformName: "Rabbit LINE Pay", data: products['coda.tha_rabbit'] },
            // { id: "coda.tha_banktransfer", channel: "", platform: "coda", platformName: "Bank transfer", data: products['coda.tha_banktransfer'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
            // { id: "paypal.card", channel: "card", platform: "paypal", platformName: 'Paypal', data: products['paypal'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
        ]
    },
    {
        area: '越南(Việt Nam)',
        areaNum: 9,
        alpha: 'VNM',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "upay.bank", channel: "", platform: "upay", platformName: "bank", data: products['upay.bank'] },
            { id: "upay.momo", channel: "", platform: "upay", platformName: "Momo", data: products['upay.momo'] },
            { id: "razer.vnm_wallet", channel: "", platform: "razer", platformName: "Razer Gold Wallet", data: products['razer.vnm.wallet'] },
            { id: "razer.vnm_pin", channel: "", platform: "razer", platformName: "Razer Gold Pin", data: products['razer.vnm.pin'] },
            { id: "upay.card.vms", channel: "vms", platform: "upay", platformName: "mobifone", data: products['upay.card.vms'] },
            { id: "upay.card.vnp", channel: "vnp", platform: "upay", platformName: "vinaphone", data: products['upay.card.vnp'] },
            { id: "upay.card.vtt", channel: "vtt", platform: "upay", platformName: "viettel", data: products['upay.card.vtt'] },
            { id: "upay.card.zing", channel: "zing", platform: "upay", platformName: "Zing", data: products['upay.card.zing'] },
            { id: "upay.card.fpt", channel: "fpt", platform: "upay", platformName: "Gate", data: products['upay.card.fpt'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
            // { id: "paypal.card", channel: "card", platform: "paypal", platformName: 'Paypal', data: products['paypal'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.ali'] },
        ]
    },
    {
        area: '沙特(المملكة العربية السعودية)',
        areaNum: 10,
        alpha: 'SAU',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.sau.wallet", channel: "", platform: "razer", platformName: 'Razer Gold Wallet', data: products['razer.sau.wallet'] },
            { id: "razer.usa.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '卡塔爾(دولة قطر)',
        areaNum: 11,
        alpha: 'QAT',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.qat.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '阿聯酋(الإمارات العربية المتحدة)',
        areaNum: 12,
        alpha: 'ARE',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.are.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "coda.are.etisalat", channel: "", platform: "coda", platformName: 'Etisalat', data: products['coda.are_etisalat'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '科威特(الكويت)',
        areaNum: 13,
        alpha: 'KWT',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.kwt.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "coda.kwt.zain", channel: "", platform: "coda", platformName: 'Zain', data: products['coda.kwt_zain'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '伊拉克(العراق)',
        areaNum: 14,
        alpha: 'IRQ',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.irq.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '巴林(البحرين)',
        areaNum: 15,
        alpha: 'BHR',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.bhr.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "coda.bhr.zain", channel: "", platform: "coda", platformName: 'Zain', data: products['coda.bhr_zain'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '約旦(الأردن)',
        areaNum: 16,
        alpha: 'JOR',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.jor.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '黎巴嫩(لبنان)',
        areaNum: 17,
        alpha: 'LBN',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.lbn.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '阿曼(سلطنة عمان)',
        areaNum: 18,
        alpha: 'OMN',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.omn.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '摩洛哥(المغرب)',
        areaNum: 19,
        alpha: 'MAR',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.mar.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '埃及(مصر)',
        areaNum: 20,
        alpha: 'EGY',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.egy.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '利比亞(ليبيا)',
        areaNum: 21,
        alpha: 'LBY',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.lby.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '突尼斯(تونس)',
        areaNum: 22,
        alpha: 'TUN',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.tun.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '阿爾及利亞(الجزائر)',
        areaNum: 23,
        alpha: 'DZA',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.dza.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '敘利亞(سوريا)',
        areaNum: 24,
        alpha: 'SYR',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.syr.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '也門(اليمن)',
        areaNum: 25,
        alpha: 'YEM',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.yem.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.usa.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '美國(USA)',
        areaNum: 26,
        alpha: 'USA',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.usa.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.us.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '新西蘭(New Zealand)',
        areaNum: 27,
        alpha: 'NZL',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.nzl.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.nzl.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '巴西(Brazil)',
        areaNum: 28,
        alpha: 'BRA',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.bra.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.bra.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '澳大利亞(Australia)',
        areaNum: 29,
        alpha: 'AUS',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.aus.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.aus.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '菲律賓(Philippines)',
        areaNum: 30,
        alpha: 'PHL',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.phl.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.phl.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '印度(India)',
        areaNum: 31,
        alpha: 'IND',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.ind.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.ind.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '歐洲(Europe)',
        areaNum: 32,
        alpha: 'EUR',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.eur.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.eur.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '緬甸(Myanmar)',
        areaNum: 33,
        alpha: 'MMR',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.mmr.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.mmr.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '土耳其(Turkey)',
        areaNum: 34,
        alpha: 'TUR',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.tur.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.tur.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '墨西哥(Mexico)',
        areaNum: 35,
        alpha: 'MEX',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.mex.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.mex.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '加拿大(Canada)',
        areaNum: 36,
        alpha: 'CAN',
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "razer.can.pin", channel: "", platform: "razer", platformName: 'Razer Gold Pin', data: products['razer.can.pin'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
        ]
    },
    {
        area: '其他地區(Other Regions)',
        areaNum: 37,
        alpha: 'OTHER',
        remote: true,
        data: [
            { id: "adyen.card", platform: "adyen", platformName: 'Credit Card/Debit Card', data: products['adyen.any.card'] },
            { id: "adyen.amex", platform: "adyen", platformName: 'American Express', data: products['adyen.any.amex'] },
            { id: "fomo.card", channel: "card", platform: "fomo", platformName: 'Debit/Credit Card', data: products['fomo.card'] },
            // { id: "paypal.card", channel: "card", platform: "paypal", platformName: 'Paypal', data: products['paypal'] },
            // { id: "fomo.ali", channel: "ali", platform: "fomo", platformName: 'Alipay', data: products['fomo.ali'] },
            { id: "p99", channel: "", platform: "p99", platformName: 'Gash Point', data: products['p99'] },
        ]
    }
];
