export default {
    "text1": "Data Tuan Rumah",
    "text2": "Data Detil",
    "text3": "Data Agensi",
    "text4": "Data Langsung Agensi",
    "text5": "Tuan Rumah Data Langsung",

    "text6": "Informasi Agensi",
    "text7": "Nama Agensi",
    "text8": "ID Pemilik Agensi",
    "text9": "Nama Panggilan Pemilik Agensi",
    "text10": "Negara",
    "text11": "Zona Waktu Data",
    "text12": "Tanggal Penandatanganan Tuan Rumah",
    "text13": "Data Langsung",
    "text14": "Periksa Data Detil",
    "text15": "Poin Pesona - Kemarin",
    "text16": "TIDAK. Suporter - Kemarin",
    "text17": "Berlaku Untuk Pengguna Mikrofon di Kamar-Kemarin",
    "text18": "Poin Pesona Diterima dalam Obrolan Pribadi - Kemarin",
    "text19": "Jam tayang-Kemarin",
    "text20": "Hari Langsung Berlaku atau Tidak - Kemarin",

    "text21": "Tuan Rumah Data Langsung",
    "text22": "Data Langsung Agensi",

    "text23": "Beralih ke bulan",
    "text24": "Beralih ke (Tanggal)",
    "text25": "Pilih Siklus",
    "text26": "Edit Bidang Numerik",
    "text27": "Waktu (tanggal/bulan)",
    "text28": "TIDAK. dari Pendukung",
    "text29": "Poin Pesona",
    "text30": "Poin Pesona Diterima di Kamar",
    "text31": "Poin Pesona Diterima dalam Obrolan Pribadi",
    "text32": "Jam Langsung",
    "text33": "Hari Langsung yang Berlaku",
	"text51": "Berlaku Untuk Pengguna Mikrofon di Kamar",
	"text52": "Jam Permainan",

    "text34": "TIDAK. dari Tuan Rumah",
    "text35": "Tanggal Penandatanganan Agensi",

    "text36": "TIDAK. dari Host Berbakat",
    "text37": "TIDAK. dari Tuan Rumah Baru",

    "text38": "ID Tuan Rumah",
    "text39": "Nama Panggilan Tuan Rumah",
    "text40": "Jam tayang yang valid",

    "text41": "Memuat Halaman Berikutnya",
    "text42": "Tidak Ada Lagi Data",
    "text43": "Edit Bidang Numerik",
    "text44": "Menyimpan",
    "text45": "Tanggal/Siklus Harus di kolom pertama, dan maksimal 5 Bidang Numerik",

    "text46": "Salinan",
    "text47": "Jam Live yang Valid: Berada di mic terus menerus selama lebih dari 20 menit akan dihitung dalam Jam Live yang Valid.",
    "text48": "Hari Siaran Langsung yang Valid: Jam Siaran Langsung yang valid melebihi 2 jam akan dihitung sebagai 1 Hari Siaran Langsung yang Valid.",
    "text49": "Ya",
    "text50": "Tidak",

}