export default {
  "recharge_amount": "Jumlah top up",
  "nickname": "Nickname",
  "confirm_recharge": "Konfirmasi top up",
  "confirm": "Yakin",
  "account_recharge": "Danai akun",
  "choose_recharge_method": "Pilih cara top up",
  "choose_recharge_amount": "Pilih jumlah top up",
  "confirm_payment": "Konfirmasi bayar",
  "text1": "Hasil Pembayaran",
  "text2": "rincian",
  "text3": "Pengecualian terjadi di layanan, silakan coba lagi",
  "text4": "Konfirmasi Status Pembayaran",
  "text5": "Apakah Anda sudah menyelesaikan pembayaran?",
  "text6": "Ya",
  "text7": "Proses pembayaran",
  "text8": "Pembayaran berhasil",
  "text9": "rincian",
  "text10": "Waktu Pembayaran",
  "text11": "Saluran Pembayaran",
  "text12": "Jumlah order",
  "text13": "Tidak",
  "text14": "berlian",
  "text15": "Pengecer",
  "text16": "isi ulang berlian",
  "text17": "Reseller Top Up"
}