export default {
    "text1": "mengingatkan",
    "text2": "Apakah Anda yakin ingin mengubah informasi akun penarikan?",
    "text3": "Batal",
    "text4": "Konfirmasi",
    "text5": "Minimal $1 setiap kali",
    "text6": "Jumlah penarikan tidak mencukupi",
    "text7": "Kesalahan format akun Payoneer",
    "text8": "rincian",
    "text9": "Catatan Penarikan",
    "text10": "Masukkan jumlah penarikan",
    "text11": " Minimal $1 setiap kali",
    "text12": "Minimal $1 setiap kali",
    "text13": "Jumlah penarikan tidak mencukupi",
    "text14": "Biaya penarikan",
    "text15": "Jumlah sebenarnya:",
    "text16": "Pilih metode penarikan",
    "text17": "Ke Akun Pemilik Agensi",
    "text18": "Informasi penarikan lengkap",
    "text19": "Akun",
    "text20": "Klik untuk memasukkan akun Payoneer，Formatnya adalah email",
    "text21": "Harap pastikan bahwa informasi yang Anda masukkan benar, jika tidak, penarikan tidak akan berhasil",
    "text22": "Harap diperhatikan bahwa setelah memilih metode penarikan ini, saldo akan langsung masuk ke rekening pemilik agensi, dan pemilik agensi harus menarik kembali ke kartu bank atau dompet digitalnya sendiri. Waktu dan jumlah kedatangan yang sebenarnya tergantung pada penarikan terakhir dari pemilik agensi.",
    "text23": "Setelah ditarik ke akun pemilik agensi, itu tidak dapat dikembalikan. Harap konfirmasi sebelum melanjutkan. Karena tingkat saluran dompet digital dan kartu bank, penarikan ini diharapkan membayar biaya penanganan sebesar %5.",
    "text24": "Daftar di Payoneer",
    "text25": "Gunakan pertama kali, Anda harus pergi ke situs web resmi Payoneer untuk mendaftar",
    "text26": "Pergi",
    "text27": "Konfirmasi informasi penarikan",
    "text28": "Metode penarikan",
    "text29": "Akun",
    "text30": "Jumlah penarikan",
    "text31": "Biaya Penanganan",
    "text32": "Jumlah sebenarnya",
    "text33": "Apakah Anda yakin akan melakukan penarikan ke rekening pemilik agensi?",
    "text34": "Perkiraan Biaya Penanganan",
    "text35": "Perkiraan Jumlah Aktual",
    "text36": "Mengajukan permohonan",
    "text37": "Pengolahan",
    "text38": "Penarikan Sukses",
    "text39": "Penarikan Gagal",
    "text40": "Aplikasi yang berhasil",
    "text41": "Jumlah sebenarnya",
    "text42": "Akun",
    "text43": "Tanggal penarikan",
    "text44": "Aplikasi penarikan akan ditinjau dan diselesaikan dalam 5 hari kerja, dan waktu kedatangan sebenarnya akan diproses oleh bank atau dompet digital;",
    "text45": "Anda dapat pergi ke [dompet-Penarikan-",
    "text46": "】kemajuan kueri;",
    "text47": "Mengajukan permohonan",
    "text48": "menarik",
    "text49": "transfer sukses"
}