export default {
  "recharge_amount": "充值金額",
  "nickname": "昵稱",
  "confirm_recharge": "確認充值",
  "confirm": "確定",
  "account_recharge": "賬戶充值",
  "choose_recharge_method": "選擇充值方式",
  "choose_recharge_amount": "選擇充值金額",
  "confirm_payment": "確認支付",
  "text1": "支付結果",
  "text2": "詳情",
  "text3": "服務異常，請重試一次",
  "text4": "支付狀態確認",
  "text5": "是否已經完成支付",
  "text6": "已支付",
  "text7": "支付中",
  "text8": "支付成功",
  "text9": "詳情",
  "text10": "支付時間",
  "text11": "支付渠道",
  "text12": "訂單號",
  "text13": "未支付",
  "text14": "鑽石",
  "text15": "幣商",
  "text16": "鑽石充值",
  "text17": "幣商鑽石充值"
}