export default {
  "recharge_amount": "Top up amount",
  "nickname": "Nickname",
  "confirm_recharge": "Confirm top up",
  "confirm": "Tentu",
  "account_recharge": "Top up",
  "choose_recharge_method": "Select a top-up method",
  "choose_recharge_amount": "Select a top-up amount",
  "confirm_payment": "Confirm payment",
  "text1": "Keputusan Pembayaran",
  "text2": "Butiran",
  "text3": "Pengecualian berlaku dalam perkhidmatan, sila cuba lagi",
  "text4": "Pengesahan Status Pembayaran",
  "text5": "Adakah anda telah menyelesaikan pembayaran?",
  "text6": "Ya",
  "text7": "Pemprosesan Pembayaran",
  "text8": "Kejayaan Pembayaran",
  "text9": "Butiran",
  "text10": "Masa Pembayaran",
  "text11": "Saluran Pembayaran",
  "text12": "Nombor Pesanan",
  "text13": "Tidak",
  "text14": "berlian",
  "text15": "Penjual semula",
  "text16": "cas semula berlian",
  "text17": "Caj Semula Ejen"
}