export default {
    "text1": "ingatkan",
    "text2": "Adakah anda pasti mahu mengubah suai maklumat akaun pengeluaran?",
    "text3": "Batal",
    "text4": "mengesahkan",
    "text5": "Min $1 setiap kali",
    "text6": "Jumlah pengeluaran yang tidak mencukupi",
    "text7": "Ralat format akaun Payoneer",
    "text8": "Butiran",
    "text9": "Rekod Pengeluaran",
    "text10": "Masukkan jumlah pengeluaran",
    "text11": " Min $1 setiap kali",
    "text12": "Min $1 setiap kali",
    "text13": "Jumlah pengeluaran yang tidak mencukupi",
    "text14": "Yuran pengeluaran",
    "text15": "Jumlah Sebenar",
    "text16": "Pilih kaedah pengeluaran",
    "text17": "Kepada Akaun Pemilik Agensi",
    "text18": "Maklumat pengeluaran lengkap",
    "text19": "Akaun",
    "text20": "Klik untuk memasukkan akaun Payoneer，Formatnya ialah e-mel",
    "text21": "Sila pastikan bahawa maklumat yang anda masukkan adalah betul, jika tidak penarikan balik tidak akan berjaya",
    "text22": "Sila ambil perhatian bahawa selepas memilih kaedah pengeluaran ini, baki akan serta-merta memasuki akaun pemilik agensi, dan pemilik agensi perlu mengeluarkan semula ke kad bank atau dompet digitalnya sendiri. Masa ketibaan dan jumlah sebenar adalah tertakluk kepada pengeluaran terakhir pemilik agensi.",
    "text23": "Selepas mengeluarkan ke akaun pemilik agensi, ia tidak boleh dikembalikan. Sila sahkan sebelum meneruskan. Disebabkan oleh kadar saluran dompet digital dan kad bank, pengeluaran ini dijangka akan membayar yuran pengendalian sebanyak %5.",
    "text24": "Daftar dengan Payoneer",
    "text25": "Gunakannya pada kali pertama, anda perlu pergi ke laman web rasmi Payoneer untuk mendaftar",
    "text26": "Pergi",
    "text27": "Sahkan maklumat pengeluaran",
    "text28": "Kaedah pengeluaran",
    "text29": "Akaun",
    "text30": "Jumlah Pengeluaran",
    "text31": "Yuran Pengendalian",
    "text32": "Jumlah Sebenar",
    "text33": "Adakah anda pasti untuk menarik balik ke akaun pemilik agensi?",
    "text34": "Anggaran Yuran Pengendalian",
    "text35": "Anggaran Jumlah Sebenar",
    "text36": "Hantar Permohonan",
    "text37": "Memproses",
    "text38": "Kejayaan Pengeluaran",
    "text39": "Pengeluaran Gagal",
    "text40": "Permohonan yang berjaya",
    "text41": "Jumlah Sebenar",
    "text42": "Akaun",
    "text43": "Tarikh pengeluaran",
    "text44": "Permohonan pengeluaran akan disemak dan diselesaikan dalam 5 hari bekerja, dan masa ketibaan sebenar adalah tertakluk kepada pemprosesan oleh bank atau dompet digital;",
    "text45": "awak boleh【dompet-menarik diri-",
    "text46": "】kemajuan pertanyaan;",
    "text47": "Permohonan Pengeluaran",
    "text48": "menarik diri",
    "text49": "pemindahan berjaya"
}