export default {
  "recharge_amount": "充值金额",
  "nickname": "昵称",
  "confirm_recharge": "确认充值",
  "confirm": "确认",
  "account_recharge": "账户充值",
  "choose_recharge_method": "选择充值方式",
  "choose_recharge_amount": "选择充值金额",
  "confirm_payment": "确认支付",
  "text1": "支付结果",
  "text2": "详情",
  "text3": "服务异常，请重试一次",
  "text4": "支付状态确认",
  "text5": "是否已经完成支付",
  "text6": "已支付",
  "text7": "支付中",
  "text8": "支付成功",
  "text9": "详情",
  "text10": "支付时间",
  "text11": "支付渠道",
  "text12": "订单号",
  "text13": "未支付",
  "text14": "钻石",
  "text15": "币商",
  "text16": "钻石充值",
  "text17": "币商钻石充值"
}