export default {
  "recharge_amount": "مبلغ الشحن",
  "nickname": "الاسم",
  "confirm_recharge": "تأكيد الشحن",
  "confirm": "تأكيد",
  "account_recharge": "شحن الحساب",
  "choose_recharge_method": "اختر طريقة الشحن",
  "choose_recharge_amount": "اختيار مبلغ الشحن",
  "confirm_payment": "تأكيد الدفع",
  "text1": "نتائج الدفع",
  "text2": "التفاصيل",
  "text3": "استثناء الخدمة، يرجى المحاولة مرة أخرى",
  "text4": "تأكيد حالة الدفع",
  "text5": "هل أكملت الدفع",
  "text6": "لا، لم أدفع",
  "text7": "جاري الدفع",
  "text8": "يتم الدفع بنجاح",
  "text9": "التفاصيل",
  "text10": "وقت الدفع",
  "text11": "قناة الدفع",
  "text12": "رقم الطلب",
  "text13": "نعم، دفعت",
  "text14": "الماست",
  "text15": "وكالة الشحن",
  "text16": "شحن الماسات",
  "text17": "شحن وكالة الشحن"
}