export default {
  "recharge_amount": "Số tiền nạp",
  "nickname": "Nickname",
  "confirm_recharge": "Xác nhận nạp",
  "confirm": "Xác nhận",
  "account_recharge": "Nạp tiền vào tài khoản",
  "choose_recharge_method": "Chọn phương thức nạp",
  "choose_recharge_amount": "Chọn số tiền nạp",
  "confirm_payment": "Xác nhận nạp",
  "text1": "Kết quả thanh toán",
  "text2": "Thông tin chi tiết",
  "text3": "Đã xảy ra ngoại lệ trong dịch vụ, vui lòng thử lại",
  "text4": "Xác nhận Trạng thái Thanh toán",
  "text5": "Bạn đã hoàn thành thanh toán chưa?",
  "text6": "Đúng",
  "text7": "Xử lý Thanh toán",
  "text8": "Thanh toán thành công",
  "text9": "Thông tin chi tiết",
  "text10": "Thời gian thanh toán",
  "text11": "Kênh thanh toán",
  "text12": "Số đơn hàng",
  "text13": "Không",
  "text14": "Kim cương",
  "text15": "Người bán lại",
  "text16": "nạp kim cương",
  "text17": "Người bán lại nạp tiền"
}