export default {
    "text1": "nhắc lại",
    "text2": "Bạn có chắc chắn muốn sửa đổi thông tin tài khoản rút tiền không?",
    "text3": "Hủy",
    "text4": "xác nhận",
    "text5": "Tối thiểu $1 mỗi lần",
    "text6": "Số tiền rút không đủ",
    "text7": "Lỗi định dạng tài khoản Payoneer",
    "text8": "Thông tin chi tiết",
    "text9": "Hồ sơ rút tiền",
    "text10": "Nhập số tiền rút",
    "text11": " Tối thiểu $1 mỗi lần",
    "text12": "Tối thiểu $1 mỗi lần",
    "text13": "Số tiền rút không đủ",
    "text14": "Phí rút tiền",
    "text15": "Số tiền thực tế:",
    "text16": "Chọn phương thức rút tiền",
    "text17": "Tới tài khoản chủ sở hữu đại lý",
    "text18": "Hoàn thành thông tin rút tiền",
    "text19": "Tài khoản",
    "text20": "Nhấp để nhập tài khoản Payoneer，Định dạng là email",
    "text21": "Vui lòng đảm bảo rằng thông tin bạn nhập là chính xác, nếu không việc rút tiền sẽ không thành công",
    "text22": "Xin lưu ý rằng sau khi chọn phương thức rút tiền này, số dư sẽ ngay lập tức vào tài khoản của chủ đại lý, và chủ đại lý cần rút về thẻ ngân hàng hoặc ví điện tử của chính mình một lần nữa. Thời gian đến và số tiền thực tế tùy thuộc vào việc rút tiền cuối cùng của chủ đại lý.",
    "text23": "Sau khi rút về tài khoản của chủ đại lý thì không trả lại được. Vui lòng xác nhận nó trước khi tiếp tục. Do tỷ lệ kênh của ví kỹ thuật số và thẻ ngân hàng, việc rút tiền này dự kiến ​​sẽ phải trả phí xử lý là% 5.",
    "text24": "Đăng ký với Payoneer",
    "text25": "Sử dụng lần đầu tiên, bạn cần truy cập trang web chính thức của Payoneer để đăng ký",
    "text26": "Đi",
    "text27": "Xác nhận thông tin rút tiền",
    "text28": "Phương thức rút tiền",
    "text29": "Tài khoản",
    "text30": "Số tiền rút",
    "text31": "Phí xử lý",
    "text32": "Số tiền thực tế:",
    "text33": "Bạn có chắc chắn rút về tài khoản của chủ đại lý không",
    "text34": "Phí xử lý ước tính",
    "text35": "Số tiền thực tế ước tính",
    "text36": "Gửi đơn đăng ký",
    "text37": "Xử lý",
    "text38": "Rút tiền thành công",
    "text39": "Rút tiền không thành công",
    "text40": "Ứng dụng thành công",
    "text41": "Số tiền thực tế:",
    "text42": "Tài khoản:",
    "text43": "Ngày rút tiền",
    "text44": "Đơn rút tiền sẽ được xem xét và hoàn thành trong 5 ngày làm việc, và thời gian đến thực tế tùy thuộc vào xử lý của ngân hàng hoặc ví điện tử;",
    "text45": "Bạn có thể đi tới 【Ví-Rút tiền-",
    "text46": "】tiến trình truy vấn;",
    "text47": "Gửi đơn đăng ký",
    "text48": "rút",
    "text49": "chuyển khoản thành công"
}