export default {
  "recharge_amount": "결제 금액",
  "nickname": "닉네임",
  "confirm_recharge": "충전 확인",
  "confirm": "확인",
  "account_recharge": "계정 충전",
  "choose_recharge_method": "결제 수단을 선택하기",
  "choose_recharge_amount": "결제 금액을 선택하기",
  "confirm_payment": "결제 확인",
  "text1": "결제 결과",
  "text2": "명세",
  "text3": "서비스 예외, 다시 시도하십시오",
  "text4": "결제 상태 확인",
  "text5": "결제가 되었나요？",
  "text6": "지불됨",
  "text7": "결제 중",
  "text8": "결제 성공",
  "text9": "명세",
  "text10": "결제시간",
  "text11": "결제채널",
  "text12": "주문 번호",
  "text13": "미지급",
  "text14": "다이아몬드",
  "text15": "리셀러",
  "text16": "다이아몬드 재충전",
  "text17": "리셀러 충전"
}